version: '3.5'

services:
  api:
    build: ../API/APIGateway
    container_name: api
    ports:
      - "8080:80"
    networks:
      - docker-network


  # users_service:
  #   build: ../Src/UsersService/UsersService
  #   container_name: users_service
  #   networks:
  #     - docker-network
  # movies_service:
  #   build: ../Src/MoviesService/MoviesService
  #   container_name: movies_service
  #   networks:
  #     - docker-network
  # reviews_service:
  #   build: ../Src/ReviewsService/ReviewsService
  #   container_name: reviews_service
  #   networks:
  #     - docker-network

  db:
   image: mcr.microsoft.com/mssql/server:2019-latest
   container_name: db
   environment:
    - "ACCEPT_EULA=Y"
    - "SA_PASSWORD=pass123!"
   ports:
    - "1433:1433"
   networks:
    - docker-network

  mongo:
    image: mongo
    container_name: mongo
    ports:
      - "27017:27017"
    networks:
      - docker-network

  elasticsearch:
   image: docker.elastic.co/elasticsearch/elasticsearch:7.8.1
   container_name: elasticsearch
   ports:
    - "9200:9200"
   environment:
    - "ES_JAVA_OPTS=-Xms512m -Xmx512m"
    - "discovery.type=single-node"
   volumes:
    - elasticsearch-data:/usr/share/elasticsearch/data
   networks:
    - docker-network

  kibana:
   image: docker.elastic.co/kibana/kibana:7.8.1
   container_name: kibana
   ports:
    - "5601:5601"
   depends_on:
    - elasticsearch
   networks:
    - docker-network

  apm:
   image: docker.elastic.co/apm/apm-server:7.8.1
   container_name: apm
   ports:
    - "8200:8200"
   depends_on:
    - kibana
   networks:
    - docker-network

  rabbitmq:
    image: rabbitmq:3-management
    container_name: rabbitmq
    ports:
     - "5672:5672"
     - "15672:15672"
    networks:
     - docker-network

  # kafka:
  #   image: wurstmeister/kafka
  #   container_name: kafka
  #   ports:
  #    - "9092:9092"
  #    - "9093:9093"
  #   networks:
  #    - docker-network

  consul:
    image: consul
    container_name: consul
    ports:
     - "8500:8500"
    networks:
     - docker-network

networks:
  docker-network:
    driver: bridge

volumes:
  elasticsearch-data:
