version: '3.5'

services:
  tyk-dashboard:
    image: tykio/tyk-dashboard:latest
    ports:
    - "3000:3000"
    - "5000:5000"
    networks:
    - tyk
    depends_on:
    - tyk-redis
    - tyk-mongo
    volumes:
    - ../ApiGateway/Tyk/dashboard:/opt/tyk-dashboard

  tyk-gateway:
    image: tykio/tyk-gateway:latest
    ports:
    - "8080:8080"
    volumes:
      - ../ApiGateway/Tyk/gateway:/opt/tyk-gateway
    networks:
      - network-gateway
      - network-microservice
      - tyk
    links:
      - users_service
      - movies_service
      - reviews_service
    depends_on:
      - consul
      - tyk-redis

  tyk-pump:
    image: tykio/tyk-pump-docker-pub:latest
    networks:
    - tyk
    depends_on:
    - tyk-redis
    - tyk-mongo
    - tyk-gateway
    volumes:
    - ../ApiGateway/Tyk/pump:/opt/tyk-pump

  tyk-redis:
    image: redis
    ports:
    - "6379:6379"
    volumes:
    - redis-data:/data
    networks:
    - tyk

  tyk-mongo:
    image: mongo:3.2
    command: ["mongod", "--smallfiles"]
    ports:
    - "27017:27017"
    volumes:
    - mongo-data:/data/db
    networks:
    - tyk

volumes:
  redis-data:
  mongo-data:

networks:
  tyk:
    #internal: true
    driver: bridge
    ipam:
      driver: default
      config:
        - subnet: 172.28.8.0/24
