version: "3.5"

services:
  apigateway:
    build: ../API/APIGateway
    container_name: apigateway
    restart: unless-stopped
    ports:
      - 8080:80
    depends_on:
      - usersservice
      - messagesservice
      - consul
    networks:
      - usersservice
      - messagesservice
      - discovery

  usersservice:
    build: ../Src/UsersService
    container_name: usersservice
    restart: unless-stopped
    depends_on:
      - consul
      - fabio
      - rabbitmq
    networks:
      - discovery
      - logging
      - rabbitmq
      - usersservice

  messagesservice:
    build: ../Src/MessagesService
    container_name: messagesservice
    restart: unless-stopped
    depends_on:
      - consul
      - fabio
      - rabbitmq
    networks:
      - discovery
      - logging
      - rabbitmq
      - messagesservice

  consul:
    image: consul
    container_name: consul
    restart: unless-stopped
    networks:
      - discovery
    ports:
      - 8500:8500
    volumes:
      - consul:/consul/data

  fabio:
    image: fabiolb/fabio
    container_name: fabio
    restart: unless-stopped
    networks:
      - discovery
    environment:
    - FABIO_REGISTRY_CONSUL_ADDR=consul:8500
    ports:
    - 9998:9998
    - 9999:9999

  grafana:
    image: grafana/grafana
    container_name: grafana
    restart: unless-stopped
    networks:
      - metrics
    ports:
      - 3000:3000
    volumes:
      - grafana:/var/lib/grafana

  jaeger:
    image: jaegertracing/all-in-one
    container_name: jaeger
    restart: unless-stopped
    networks:
      - logging
    ports:
      - 5775:5775/udp
      - 5778:5778
      - 6831:6831/udp
      - 6832:6832/udp
      - 9411:9411
      - 14268:14268
      - 16686:16686

  mongo:
    image: mongo
    container_name: mongo
    restart: unless-stopped
    networks:
      - mongo
    ports:
      - 27017:27017
    volumes:
      - mongo:/data/db

  # prometheus:
  #   build: ./prometheus
  #   container_name: prometheus
  #   restart: unless-stopped
  #   ports:
  #     - '9090:9090'
  #   # volumes:
  #   #   - prometheus:/prometheus

  rabbitmq:
    image: rabbitmq:3-management
    container_name: rabbitmq
    restart: unless-stopped
    ports:
      - 5672:5672
      - 15672:15672
    networks:
      - rabbitmq
    volumes:
      - rabbitmq:/var/lib/rabbitmq

  redis:
    image: redis
    container_name: redis
    restart: unless-stopped
    ports:
      - 6379:6379
    networks:
      - redis
    volumes:
      - redis:/data

  seq:
    image: datalust/seq
    container_name: seq
    restart: unless-stopped
    environment:
      - ACCEPT_EULA=Y
    networks:
      - logging
    ports:
      - 5341:80
    volumes:
      - seq:/data

  vault:
    image: vault
    container_name: vault
    restart: unless-stopped
    networks:
      - storage
    environment:
      - VAULT_ADDR=http://127.0.0.1:8200
      - VAULT_DEV_ROOT_TOKEN_ID=secret
    cap_add:
      - IPC_LOCK

networks:
  discovery:
  metrics:
  mongo:
  rabbitmq:
  redis:
  logging:
  storage:
  usersservice:
  messagesservice:

volumes:
  consul:
    driver: local
  grafana:
    driver: local
  mongo:
    driver: local
  prometheus:
    driver: local
  rabbitmq:
    driver: local
  redis:
    driver: local
  seq:
    driver: local